Wet-Boys/LookingGlass

LookingGlass/BasePlugin.cs
LookingGlass/ItemStats/ItemStats.cs
LookingGlass/StatsDisplay/StatsDisplayClass.cs

This adds two new settings to the mod:
- **Full Item Description On Pickup**: This is really a separation of one setting into two separate ones. Now you can separately toggle whether you want the short or full descriptions on the item pickup notification, without losing out on the more detailed stats on the Tab screen.
- **StatsDisplay update interval**: Lets the stats update more than once every 1/3rd second. I'm guessing the low update rate was done out of an abundance of caution for performance, but having the option to make it more responsive (with a note that it may affect performance) seems like a good idea to me.
If you'd prefer me to separate these into individual PRs, I can do that, but I figured it's simplest for now to combine them.
----
also bonus fun fact: this was initially …

Add two new settings: Full Item Description On Pickup and StatsDisplay Update Interval

---

LookingGlass/LookingGlass.csproj
LookingGlass/StatsDisplay/StatsDisplayClass.cs
LookingGlass/StatsDisplay/StatsDisplayDefinitions.cs
Thunderstore/thunderstore.toml

fun fact, i had velocity and update rate PRs in the works & got beaten to the punch on both counts, gg lol. gives me hope that this project is so active though. anyway, two commits that:
- let update go faster (you can see the difference on a high refresh rate monitor)
- make speed and velocity always show exactly two decimal places & have leading whitespace; this is important for `<mspace>` shenanigans which are in turn necessary for legibility if a number is changing super fast
- let you change the panel height yourself (the estimation falls flat on its face if you mix font sizes)
in combination, a format string like the following:
```
<align="center">Stats:</align>
<size=70%>
<size=80%><indent=0.75em>Speed: <pos=4em><mspace=0.5em>[speed]</mspace>
Velocity: …
```

a few misc. StatsDisplay changes

---

LookingGlass/ItemStats/ItemDefinitions.cs
LookingGlass/ItemStats/ItemStats.cs
LookingGlass/ItemStats/ItemStatsDef.cs
LookingGlass/StatsDisplay/StatsDisplayDefinitions.cs
LookingGlass/Utils.cs

Looks like a big update but I did the following:
- fixed luck display calculation for critWithLuck, bleedChanceWithLuck, and instakillChance
- updated item stats to use luck whenever possible for chance effects that are affected by luck
- added a few more useful MeasurementUnits and ValueTypes

Item Stats Luck Support

---

.editorconfig
LookingGlass.sln
LookingGlass/LookingGlass.csproj

This changes the severity of Publicizer001 (warning about using private members) to be a suggestion rather than a full-blown warning. I agree it's not a bad idea to mark usages of private members, hence why I opted not to hide it entirely, but it also _really_ does not need to be spamming the output on every build.

Add .editorconfig to make the publicizer warnings quieter

---

LookingGlass/CommandItemCount/CommandItemCount.cs
LookingGlass/ItemStats/ItemStats.cs

This makes a couple minor fixes to the Command menu hooks, both related to the "With one more stack" feature:
- Restricts it to only show up on CommandPickerPanel and OptionPickerPanel. This excludes scrappers and the eggs from the Devotion artifact, since in those cases you're giving _away_ items rather than gaining items.
- I made it specifically show up on _only_ those two panels, rather than excluding it from ScrapperPickerPanel and LemurianEggPickerPanel. This means it could potentially exclude panels added by mods, but IMO it's probably less confusing to default to not showing the message, rather than default to showing it.
- Improves grammar of the message (`With one more stack than you have` -> `With one more stack, you will have`)

Fixes to Command menu hooks

---

LookingGlass/ItemStats/ItemStats.cs
LookingGlass/ItemStats/ProcCoefficientData.cs

Aimed to address issue #62.
Adds only the Proc Coefficient data when hovering over ability during the game.
Does not work for Void Fiend's corrupted skills (Corrupted Drown)

Added Proc Coefficient data to ability description

---

LookingGlass/AutoSortItems/AutoSortItemsClass.cs
LookingGlass/Utils.cs

Bit of a bigger feature this time, this overhauls the sorting settings to be more customizable.
- **Tier Order:** A string setting that allows you to define the order in which item tiers should be sorted, with each tier separated by a space. Duplicate or invalid tiers are simply ignored, and missing tiers are added afterward according to the game's internal tier ordering. Defaults to `Lunar VoidBoss Boss VoidTier3 Tier3 VoidTier2 Tier2 VoidTier1 Tier1`. This ***replaces*** the Tier Descending settings.
- **Tier Order Preset Buttons:** Allows you to choose between two presets for the Tier Order option, descending (same as default) and ascending (reverse of default). Mostly for convenience since I killed the Tier Descending checkbox, as well as a convenient way to get back to the default if …

More options for item sorting

---

LookingGlass/ItemStats/ItemStats.cs

Some items do not have description (#53). This code uses pickup text when item does not have a description.

Fixed items with no descriptions

---

LookingGlass/ItemStats/ItemDefinitions.cs
LookingGlass/ItemStats/ItemStats.cs
LookingGlass/ItemStats/ItemStatsDef.cs
LookingGlass/ItemStats/ProcCoefficientData.cs

This PR is a continuation of https://github.com/Wet-Boys/LookingGlass/pull/79.
It aims to add to the description of a skill:
- how likely is an item to proc of a skill
- how many items do you need for the likelihood of item proccing to be 100%
I changed how functions calculating item probabilities are called to include Proc Coefficient and to take luck (float) as an argument instead of passing whole CharacterMaster. This was necessary to calculate item count needed to cap, as luck in this case does not matter.

Calculate probability for items with proc coefficient 

---

LookingGlass/CommandItemCount/CommandItemCount.cs

Another pretty neat feature if I do say so myself! This makes a couple changes to the item picker menus:
- When item counts are on, having 0 stacks of an item shows a grayed out "x0" instead of not having a number at all. Comes with an option to disable. This helps a little with visual consistency IMO, but was primarily to assist with the main feature...
- **Show Corrupted Items:** A new setting. If you have corrupted versions of an item, it'll show the count + description for the corrupted version underneath the normal ones, as well as showing stats for the corrupted version instead of the normal version.
It's probably easiest to understand with a picture:
Tested and working with modded void items as well (or at least the ones from Spikestrip and Tinker's Satchel). I'm not totally sure …

"Show Corrupted Items" command menu feature

---

LookingGlass/ItemStats/ItemDefinitions.cs

For some reason #70 (specifically https://github.com/Wet-Boys/LookingGlass/pull/70/commits/550bf424279e9362d3f15e37e5a26c2f9af51788) commented out a bunch of item stat definitions, so they won't show any stats ingame. I'm not sure why exactly, maybe because all those particular items stack trivially and it was deemed not necessary? Regardless, I think it's better to be consistent and show stats for all vanilla items - I really thought this was a bug at first.
(While I was at it I also changed Defiant Gouge to show enemy strength as a percentage rather than as a flat number.)

Uncomment a bunch of stat definitions

---

LookingGlass/ItemStats/ItemStats.cs

Forces the game to use pickupToken for description when descriptionToken does not return description. Finished addressing #53. 
I did not check if it worked on pickup earlier and it only did when hovering over an item in the inventory (sorry >_<). This should do it for picking up a new item, including when the bottle is broken

Fixed pickup description for items with no description

---

LookingGlass/CommandItemCount/CommandItemCount.cs
LookingGlass/CommandItemCount/ItemCorruptionInfo.cs
LookingGlass/ItemStats/ItemStats.cs

After I was finished with Show Corrupted Items for the command menu I realized it should probably work the other way too - if you're about to choose a void item, it should show how many of the corresponding normal item you have. So, I did that.
The specific internal changes worth noting are:
- a hook on `ContagiousItemManager.InitTransformationTable` to create a one-to-many `transformedToOriginal` lookup dict, which the game does not seem to have by itself
- the creation of a new `ItemCorruptionInfo` class to pass around data, which seems cleaner than having a bunch of extra parameters
- also a `CorruptionType` enum since now we need to handle going both ways
Also I changed the "with one more" message again:
- if you already have the item, it now says "With another stack" instead of "With …

Make "Show Corrupted Items" also work the other way

---

LookingGlass/ItemStats/ItemStats.cs

Changes Purity cooldown calculations to use `calculateValuesNew`, since `calculateValues` was removed. This is also causing NullReferenceException log spam so would be cool to have this in soon. (I know I can merge it myself but I don't have perms to upload to Thunderstore and wouldn't know how to use them even if I did so I don't feel there's much of a point lol)

fix Purity cooldown calculations being broken

---

LookingGlass/ItemStats/ItemStats.cs
LookingGlass/Utils.cs

As requested in #92, this makes chances capping at 100% a configurable option, on by default but can now be turned off to let chances go above 100%. For interactions with luck I just chose to match BetterUI's behavior, which is effectively to modulo the chance before applying luck calculations to it (so for instance with +1 luck, 10% chance becomes 19% and 50% becomes 75%, so to match that a 110% chance becomes 119% and a 150% chance becomes 175%).

add "Cap Chance Percentage" setting

---

LookingGlass/ItemStats/ItemDefinitions.cs
LookingGlass/ItemStats/ProcCoefficientData.cs

Added up the new stats calculations for the new SotS items.
- A fair warning, a lot of them seem to have wrong descriptions, the calculations i have were pulled out from the code of the game, i've put notes each times the calculation didn't match up with the description.
- I've used the calculateValues in a few places to provide some extra data depending on buffs currently active.
- I also added in the proc coefficients for the new attacks, i believe i wrote down every value that is explicitly set (the rest should be 1, as it is by default)
- i also do still have the code i used to pulled it out, i could add it in a comment if needed for the future.

Added seekers of the storm items

---

LookingGlass/ItemStats/ItemDefinitions.cs

Makes the razorwire targets stat measurement units into number(previously meters). Meters of enemies doesn't make sense.

Razorwire targets isn't in meters

---

LookingGlass/EquipTimerFix/CooldownFixer.cs
LookingGlass/ItemStats/ItemStats.cs

Changed the logic behind skill cooldown calculations to work with the skill's saved scaling values instead of checking player inventory for certain vanilla items. I'm pretty sure % CDR is applied before flat CDR, so I did baseCD * %CDR - flatCDR.
Also formatted the float result to 2 decimal places (0.00).

Fix cooldown values not receiving reductions from non-vanilla items

---

LookingGlass/ItemStats/ItemStats.cs
LookingGlass/StatsDisplay/StatsDisplayDefinitions.cs

1. Add unit to `saferSpacesCD` stat display def string
- Append `s` *(for seconds)* to the end of the string for Safer Spaces cooldown, similar to how Tougher Times appends `%`.
- This should be done in the definition rather than the stats display string config option, since:
- using the definition would allow the default styling colour to be applied
- using the config option would yield `N/As` rather than just `N/A`
2. Separate equipment description from stats
- Add an additional newline between the equipment's description and the cooldown stats
- Improve readability
- Make consistent with item tooltips

Adjust equipment description and saferSpacesCD stat display def string

---

LookingGlass/AutoSortItems/AutoSortItemsClass.cs
LookingGlass/BasePlugin.cs
LookingGlass/CommandItemCount/CommandItemCount.cs
LookingGlass/CommandWindowBlur/NoWindowBlur.cs
LookingGlass/EscapeToCloseMenu/ButtonsToCloseMenu.cs
LookingGlass/LookingGlass.csproj
LookingGlass/StatsDisplay/StatsDisplayDefinitions.cs

Move where the sorting takes place for PickupPickerPanel from RoR2.PickupPickerController.OnDisplayBegin to RoR2.UI.PickupPickerPanel.SetPickupOptions because in multiplayer there is a lot of weirdness. This fixes bug https://github.com/Wet-Boys/LookingGlass/issues/65
As a client in multiplayer when OnDisplayBegin is called the Options list will be (effectively) garbage data leftover from the previous time a PickupPickerPanel was opened. As a client, SetPickupOptions is called twice when opening a scrapper/command, the first time from OnDisplayBegin, and the 2nd time from other netcode. The first call will contain garbage data, the 2nd will have correct data. This behavior is only true in multiplayer, in singleplayer SetPickupOptions is only called once.
Because of these changes, …

Restructure PickupPickerPanel sorting (scrappers, command, etc..) to work better in multiplayer
